# ottrent settings
APPLICATION_PATH_LOG = '/usr/log/'
APPLICATION_LOGLEVEL_CONSOLE = 10 # debug 
APPLICATION_LOGLEVEL_FILE = 10 # debug
APPLICATION_LOG_LEVEL = 10 # debug
APPLICATION_MAINLOGGER = 'otrrentworker'
APPLICATION_PATH_TMP = '/tmp'
APPLICATION_PATH_TORRENTS = '/usr/torrents'
APPLICATION_PATH_OTRKEYS = '/usr/otrkeys'
APPLICATION_PATH_VIDEOS = '/usr/videos'

# azure storage settings
AZURE_REQUIRE_ENCRYPTION = True
AZURE_KEY_IDENTIFIER = 'otrrentapi'