# ottrent settings
APPLICATION_PATH_LOG = '/usr/log/'
APPLICATION_LOGLEVEL_CONSOLE = 20 # Info 
APPLICATION_LOGLEVEL_FILE = 20 # Info
APPLICATION_LOG_LEVEL = 20 # Info
APPLICATION_MAINLOGGER = 'otrrentetl'
APPLICATION_ETL_INTERVAL = 86400
APPLICATION_QUEUE_INTERVAL = 300

